# Exercise 1

### Cleaned Data importing

In [4]:
# basic imports
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'
import math
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# reading the data
data = pd.read_csv("data/clean_data.csv", sep=',')
data = data.replace([np.inf, -np.inf], np.nan).dropna()
print("data shape = ")
print(data.shape)
# Display the first 10 rows of the dataset. Only 13 columns for space reasons
print("Fist 13 columns :")
data.ix[:10,:13]

data shape = 
(1419, 19)
Fist 13 columns :


Unnamed: 0  playerShort  redCards  leagueCountry  yellowCards  victories  \
0            0            0         0              0           19        247   
1            1            1         1              2           42        141   
2            2            2         0              0           11        200   
3            3            3         1              0           31        150   
4            4            4         2              1            8         41   
5            5            5         0              1           11         41   
6            6            6         0              1            0          8   
7            7            7         0              1            0          0   
8            8            8         2              1           21         34   
9            9            9         1              2            3         17   
10          10           10         0              0            2         16   

    yellowReds  black  weight   meanExp  goals    birthday   meanIAT  
0            0      0    71.0  0.494575      9  08.11.1979  0.346459  
1            0      0    73.0  0.449220     62  04.09.1986  0.348818  
2            0      0    63.0  0.491482     31  16.04.1987  0.345893  
3            0      0    76.0  0.514693     39  26.12.1990  0.346821  
4            4      0    73.0  0.335587      1  17.03.1990  0.331600  
5            1      1    74.0  0.296562      3  17.01.1988  0.320079  
6            0      1    80.0  0.400818      0  30.03.1992  0.341625  
7            0      1    83.0  0.417225      0  19.08.1990  0.355406  
8            0      1    68.0  0.429630      3  20.03.1990  0.348178  
9            0      1    70.0  0.361068      0  02.07.1994  0.342072  
10           0      1    78.0  0.536408      0  11.11.1992  0.354566

In [5]:
# Display the other columns too
print("the other columns : ")
data.ix[:10,13:19]

the other columns : 


games  defeats  ties  club              position  height
0     654      228   179    34           Center Back   182.0
1     336      122    73    91  Attacking Midfielder   183.0
2     412      115    97    83      Right Midfielder   165.0
3     260       68    42     6     Center Midfielder   178.0
4     124       43    40    51           Center Back   180.0
5      97       33    23    36      Right Midfielder   180.0
6      24        8     8    80            Goalkeeper   189.0
7       3        2     1    36            Goalkeeper   188.0
8     121       62    25    78  Defensive Midfielder   180.0
9      50       25     8    77         Left Fullback   179.0
10     36       12     8    48     Center Midfielder   180.0

### Define features and labels

In [6]:
# labels
data_y = data['black']
data_y.head()

0    0
1    0
2    0
3    0
4    0
Name: black, dtype: int64

In [7]:
# features
data_x = data.drop(data.columns[[7,11,17]], axis=1).astype(float)
data_x.dtypes

Unnamed: 0       float64
playerShort      float64
redCards         float64
leagueCountry    float64
yellowCards      float64
victories        float64
yellowReds       float64
weight           float64
meanExp          float64
goals            float64
meanIAT          float64
games            float64
defeats          float64
ties             float64
club             float64
height           float64
dtype: object

In [8]:
data_x.ix[:10,:13]

Unnamed: 0  playerShort  redCards  leagueCountry  yellowCards  victories  \
0          0.0          0.0       0.0            0.0         19.0      247.0   
1          1.0          1.0       1.0            2.0         42.0      141.0   
2          2.0          2.0       0.0            0.0         11.0      200.0   
3          3.0          3.0       1.0            0.0         31.0      150.0   
4          4.0          4.0       2.0            1.0          8.0       41.0   
5          5.0          5.0       0.0            1.0         11.0       41.0   
6          6.0          6.0       0.0            1.0          0.0        8.0   
7          7.0          7.0       0.0            1.0          0.0        0.0   
8          8.0          8.0       2.0            1.0         21.0       34.0   
9          9.0          9.0       1.0            2.0          3.0       17.0   
10        10.0         10.0       0.0            0.0          2.0       16.0   

    yellowReds  weight   meanExp  goals   meanIAT  games  defeats  
0          0.0    71.0  0.494575    9.0  0.346459  654.0    228.0  
1          0.0    73.0  0.449220   62.0  0.348818  336.0    122.0  
2          0.0    63.0  0.491482   31.0  0.345893  412.0    115.0  
3          0.0    76.0  0.514693   39.0  0.346821  260.0     68.0  
4          4.0    73.0  0.335587    1.0  0.331600  124.0     43.0  
5          1.0    74.0  0.296562    3.0  0.320079   97.0     33.0  
6          0.0    80.0  0.400818    0.0  0.341625   24.0      8.0  
7          0.0    83.0  0.417225    0.0  0.355406    3.0      2.0  
8          0.0    68.0  0.429630    3.0  0.348178  121.0     62.0  
9          0.0    70.0  0.361068    0.0  0.342072   50.0     25.0  
10         0.0    78.0  0.536408    0.0  0.354566   36.0     12.0

In [9]:
data_x.ix[:10,13:16]

ties  club  height
0   179.0  34.0   182.0
1    73.0  91.0   183.0
2    97.0  83.0   165.0
3    42.0   6.0   178.0
4    40.0  51.0   180.0
5    23.0  36.0   180.0
6     8.0  80.0   189.0
7     1.0  36.0   188.0
8    25.0  78.0   180.0
9     8.0  77.0   179.0
10    8.0  48.0   180.0

### Split data into train and test data

In [10]:
data_y = np.asarray(data_y)
data_x = data_x.as_matrix()

In [11]:
# take ratio*100% of the data to train the model and keep (1-ratio)*100% of the data to validate the model
def split_data(x, y, ratio, seed=1):
    """split the dataset based on the split ratio."""
    # set seed
    np.random.seed(seed)
    # ***************************************************
    tr_len = np.floor(x.shape[0]*ratio).astype(int)
    train_idx = np.random.choice(range(x.shape[0]),tr_len, replace=False)
    test_idx = np.delete(range(x.shape[0]),train_idx)
    # ***************************************************
    y_train = y[train_idx]
    y_test = y[test_idx]
    x_train = x[train_idx,:]
    x_test = x[test_idx,:]
    return x_train,y_train,x_test,y_test

# randomly split the data
data_x_train,data_y_train,data_x_test,data_y_test = split_data(data_x,data_y, ratio = 0.6)

In [12]:
print(data_y_train.shape)
print(data_y_test.shape)

(851,)
(568,)


### Random Forest Classifier

Train a sklearn.ensemble.RandomForestClassifier that given a soccer player description outputs his skin color.

In [13]:
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(data_x_train, data_y_train)

make predictions using the model

In [14]:
data_y_pred = clf.predict(data_x_test)

prediction mean square error 

In [15]:
mse = mean_squared_error(data_y_test, data_y_pred) 
mse

0.1619718309859155

In [16]:
clf.score(data_x_test, data_y_test)

0.8380281690140845

In [26]:
# different ratio values
ratio = np.arange(0.1,1.,0.1)
tr_score = np.zeros(ratio.shape)
te_score = np.zeros(ratio.shape)


for i in  np.arange(len(ratio)):
    data_x_train,data_y_train,data_x_test,data_y_test = split_data(data_x,data_y, ratio[i])
    clf = clf.fit(data_x_train, data_y_train)
    tr_score[i] = clf.score(data_x_train, data_y_train)
    te_score[i] = clf.score(data_x_test, data_y_test)

In [27]:
ratio


array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [28]:
tr_score

array([ 0.97163121,  0.97173145,  0.98823529,  0.98236332,  0.98025388,
        0.98589894,  0.98489426,  0.98942731,  0.98747063])

In [29]:
te_score

array([ 0.84115806,  0.83978873,  0.83702213,  0.82276995,  0.81830986,
        0.83802817,  0.83802817,  0.82042254,  0.87323944])

Show how different parameters passed to the Classifier affect the overfitting issue. 

Perform cross-validation to mitigate the overfitting of your model.

In [22]:
def build_k_indices(y, k_fold, seed):
    """build k indices for k-fold."""
    num_row = y.shape[0]
    interval = int(num_row / k_fold)
    np.random.seed(seed)
    indices = np.random.permutation(num_row)
    k_indices = [indices[k * interval: (k + 1) * interval]
                 for k in range(k_fold)]
    return np.array(k_indices)

def cross_validation(y, x, k_indices, k):
    # ***************************************************
    # get k'th subgroup in test, others in train
    # ***************************************************
    te_idx = k_indices[k-1]
    tr_idx = np.concatenate([k_indices[0:k-1],k_indices[k+1:len(k_indices)]]).ravel()
    te_x = x[te_idx,:]
    te_y = y[te_idx]
    tr_x = x[tr_idx,:]
    tr_y = y[tr_idx]
    # ***************************************************
    # Random Forest Classifier
    # ***************************************************
    clf.fit(tr_x, tr_y)
    # ***************************************************
    # calculate the loss for train and test data
    # ***************************************************
    tr_score = clf.score(tr_x, tr_y)
    te_score = clf.score(te_x, te_y)
    return tr_score, te_score

In [24]:
def cross_validation_demo():
    seed = 1
    k_fold = 10
    # split data in k fold
    k_indices = build_k_indices(data_y, k_fold, seed)
    # define lists to store the loss of training data and test data
    score_tr = []
    score_te = []
    # ***************************************************
    # cross validation
    # ***************************************************
    for k in np.r_[1:k_fold+1]:
        tr_score,te_score = cross_validation(data_y, data_x, k_indices, k)
        print("k = {ind}, train data score = {tr_s}, test data score = {te_s}".format(ind=k,tr_s=tr_score,te_s=te_score))
        score_tr = np.r_[score_tr, tr_score]
        score_te = np.r_[score_te, te_score]

cross_validation_demo()

k = 1, train data score = 0.9884751773049646, test data score = 0.8581560283687943
k = 2, train data score = 0.9778368794326241, test data score = 0.8581560283687943
k = 3, train data score = 0.9822695035460993, test data score = 0.8085106382978723
k = 4, train data score = 0.9787234042553191, test data score = 0.8156028368794326
k = 5, train data score = 0.975177304964539, test data score = 0.8723404255319149
k = 6, train data score = 0.9822695035460993, test data score = 0.851063829787234
k = 7, train data score = 0.9796099290780141, test data score = 0.7943262411347518
k = 8, train data score = 0.974290780141844, test data score = 0.900709219858156
k = 9, train data score = 0.9813829787234043, test data score = 0.7801418439716312
k = 10, train data score = 0.9850275807722616, test data score = 0.8297872340425532


Once you assessed your model, inspect the feature_importances_ attribute and discuss the obtained results. 

With different assumptions on the data (e.g., dropping certain features even before feeding them to the classifier), can you obtain a substantially different feature_importances_ attribute?

BONUS: plot the learning curves against at least 2 different sets of parameters passed to your Random Forest. To obtain smooth curves, partition your data in at least 20 folds. Can you find a set of parameters that leads to high bias, and one which does not?